# Generated by Django 5.0.2 on 2024-04-18 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingphoto",
            name="created_at",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.listing"
            ),
        ),
    ]
