# Generated by Django 5.0.2 on 2024-04-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="username",
            field=models.TextField(blank=True, null=True),
        ),
    ]
