# Generated by Django 5.0.2 on 2024-04-21 10:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="profiles/default.jpg", upload_to=api.models.uploadListingImage
            ),
        ),
    ]
