# Generated by Django 5.0.2 on 2024-04-18 23:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_listingphoto_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name="listingphoto",
            name="created_at",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.listing",
                to_field="created_at",
            ),
        ),
    ]
