# Generated by Django 5.0.2 on 2024-04-21 17:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="profiles/default.png",
                upload_to=api.models.uploadProfilePicture,
            ),
        ),
    ]
