# Generated by Django 5.0.2 on 2024-04-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_listing_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
