export const LISTINGS_REQUEST = 'LISTINGS_REQUEST';
export const LISTINGS_SUCCESS = 'LISTINGS_SUCCESS';
export const LISTINGS_FAIL = 'LISTINGS_FAIL';
export const LISTINGS_CREATE_REQUEST = 'LISTINGS_CREATE_REQUEST';
export const LISTINGS_CREATE_SUCCESS = 'LISTINGS_CREATE_SUCCESS';
export const LISTINGS_CREATE_FAIL = 'LISTINGS_CREATE_FAIL';